spring:
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
  datasource:
    url: "jdbc:postgresql://localhost/postgres"
    username: postgres
    password: 2772
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
jwt:
  token:
    expired: 3600000
server:
  port: 8080
